# Generated by Django 3.1.7 on 2021-03-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_searches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='skills',
        ),
    ]
